### PR TITLE
AddOffset optimization

### PR DESCRIPTION
**Pull request by xtonik**
### SUMMARY
Computation skips of shifted containers that would be discarded due to out of bounds keys in the case of container unaligned offsets. This solves #544.

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by lemire** [comment]
Looks good.

+1

**Comment by lemire** [comment]
@xtonik Would you consider extending this optimization to `MutableRoaringBitmap.java`? We try to keep our code in sync.

**Comment by xtonik** [comment]
[It is done already](https://github.com/RoaringBitmap/RoaringBitmap/pull/669/commits/6c554767b3ef09dc04a6adb31397d79be1469cce), or am I wrong?

**Comment by lemire** [comment]
Fantastic. Merging.

**Pull request merged**
