### PR TITLE
implement workshyand for iterator inputs

### PR DESCRIPTION
**Pull request by richardstartin**
to complete https://github.com/apache/druid/pull/9987

### CODE REVIEW

**Comment by lemire** [comment]
@richardstartin What is the status of this PR?

It looks like the coverage "error" can be ignored (-0.003%... really?).

**Comment by richardstartin** [comment]
I would like to merge it

**Comment by lemire** [comment]
Ok. I am going to merge this and issue a whole new release.

**Comment by lemire** [comment]
I think that this is more than a patch release. :-)

**Comment by lemire** [comment]
Merge. I have created a 0.9.1 release which includes your version with a javadoc fix.

**Comment by lemire** [comment]
I think version 0.9.0 made it but maven central won't sync 0.9.1 for some unknown reason. You should be able to use 0.9.0 right away.

**Pull request merged**
