### PR TITLE
Fix RunContainer.andCardinality(RunContainer)

### LINKED ISSUE #153: RoaringBitmap.andCardinality is not reflexive with run containers
RoaringBitmap.andCardinality should return the cardinality of the bitmap when the two bitmaps are identical. RoaringBitmap.equals respects this relation, but RoaringBitmap.andCardinality fails when there are run containers in the bitmap.

The second assertion below fails, whereas the first does not.

   ```
@Test
    public void testAndCardinality() {
        RoaringBitmap baseline = new RoaringBitmap();
        baseline.add((1L << 16) + 1, 1L << 18);
        baseline.add((1L << 19) + 1, 1L << 20);
        baseline.add((1 << 21) + 1);
        baseline.add((1 << 21) + 3);
        baseline.add((1 << 21) + 5);
        assertEquals(baseline, RoaringBitmap.and(baseline, baseline));
        assertEquals(baseline.getCardinality(), RoaringBitmap.andCardinality(baseline, baseline));
    }
```

java.lang.AssertionError: 
Expected :720897
Actual   :1

### PR DESCRIPTION
**Pull request by gssiyankai**
Fixes #153

### CODE REVIEW

**Comment by openkappa** [comment]
I have a couple of pull requests (#149) that depend on this for correctness. Should I wait for this to merge and then rebase before submitting?

**Comment by gssiyankai** [comment]
You can merge my branch into yours for the time being.

**Comment by lemire** [comment]
LGTM.

**Comment by lemire** [comment]
I'll issue an immediate release based on this, despite the fact that we have outstanding PRs.

**Pull request merged**
