### PR TITLE
Update maven dependency

### PR DESCRIPTION
**Pull request by blacelle**
Update of Maven dependency versions

### CODE REVIEW

**Comment by lemire** [comment]
Was this a bad idea?

**Comment by blacelle** [comment]
@lemire This has been produced by a robot I'm working on. I did not expect it to open a PR as given bot is not ready yet. Still it executed itself on this repo as I check its behavior on various repository. Once a MVP is stable, I would be happy to let it open a clear PR.

**Comment by lemire** [comment]
What is the bot supposed to do?

**Comment by blacelle** [comment]
Upgrade dependencies

**Pull request closed without merging**
