### PR TITLE
Fix release process

### PR DESCRIPTION
**Pull request by blasd**

### CODE REVIEW

**Comment by blasd** [comment]
It takes roughly 7 minutes on my machine.

In JMH:
Tests run: 1728, Failures: 0, Errors: 0, Skipped: 288

**Comment by blasd** [comment]
@Kineolyan Do you confirm mvn release plugin uses profiles in releaseProfiles only for mvn perform ? I suggest then using <arguments>-Prelease ${arguments}</arguments> so that additional -Darguments are combined with -Prelease which enables skipping tests also for release:perform

**Comment by blasd** [comment]
mvn release:clean release:prepare -DdryRun=true -Darguments="-DskipTests"
-> 50 seconds

mvn release:clean release:prepare -DdryRun=true
-> 3 minutes, with tests only in roaringbitmap, JMH is fully skipped

**Comment by richardstartin** [comment]
the log file is going to be ignored, right?

**Comment by blasd** [comment]
I implemented @Kineolyan suggestion so that all tests are skipped in mvn release:perform step. I can not guarantee it works until next release.

I tried restricting JMH tests with `<argLine>-DBITMAP_TYPES=ROARING_ONLY</argLine>` in release profile but it seems not working as expected. Anyway, current version skip fully jmh in the release process.

@richardstartin Which log file ?

**Comment by lemire** [comment]
Do you want me to merge and try to issue a release?

**Comment by richardstartin** [comment]
https://github.com/blasd/RoaringBitmap/blob/b6c82276dd38fa764ed638cc9889b61e1778bc09/log

**Comment by blasd** [comment]
@lemire I would at least wait for +1 for someone. 

@richardstartin spotted some stupid log file remaining in the commits :S.

Let me clean this first

**Comment by blasd** [comment]
This branch is cleaned

@lemire I would wait a +1 from @richardstartin or @Kineolyan (or anybody else) before merging and trying a release. About your settings.xml, I changed the configuration so that we rely on the historical serverId

**Comment by richardstartin** [comment]
@blasd yours isn’t a position I envy, without a sane way of testing the changes. Without that facility myself I can’t support or oppose this change - I only looked to see where the +217kloc came from. The only thing you can do is merge and try it out.

**Comment by blasd** [comment]
@richardstartin Thanks a lot for having spotted it anyway. I must be kind of masochist as I am concurrently refactoring pom.xml's for another team ; I'll know the correctness of my changes only after another guy deployed the compiled jar to some datalake...

@lemire I guess we can go for a try

**Comment by richardstartin** [comment]
@blasd Gradle ;)

**Comment by lemire** [comment]
I'll merge and issue a release while praying to the Java Gods.

**Pull request merged**
