### PR TITLE
Implement RelativeRangeConsumer and forAllInRange APIs

### PR DESCRIPTION
**Pull request by larsk-db**
This PR provides the implementation for the APIs discussed in #479.

- It adds a new consumer interface called `RelativeRangeConsumer` which has methods for both present and absent values, as well as individual value and value range variants for both.
- It also adds a method `forAllInRange` to `RoaringBitmap` and `Roaring64Bitmap` which takes such a `RelativeRangeConsumer` as well as the bounds of the range.
- Additionally, it provides a similar variant with `forEach`-semantics, called `forEachInRange`, which reuses the `forAllInRange` code and simply ignores the absent values via an adapter class.

Note: I apologise for huge PR. Most of it's length stems from tests for all the different containers, as well as per container `forAll...` methods that specialise the range (whole container vs. starts in container vs. ends in container vs. fully within container). It was easy to determine these cases above the container-level and the specialisations are (in my opinion) easier to understand and also save some conditionals (of which there are already more than enough). But they come at the cost of *some* code duplication.

### CODE REVIEW

**Comment by lemire** [comment]
@richardstartin Care to have a look?

**Review by richardstartin — COMMENTED** [review]
I’ve had a quick look and it looks neat, I haven’t spotted any obvious flaws. The only thing that jumps out at me is I would prefer to see shifts to divisions and multiplications - it makes no difference to peak performance but using shifts warms up faster and produces less compilation work. I don’t expect to find anything in particular, but I would like to test this thoroughly before merging, but I won’t get time to do that for a few days.

**Comment by larsk-db** [comment]
> I’ve had a quick look and it looks neat, I haven’t spotted any obvious flaws. The only thing that jumps out at me is I would prefer to see shifts to divisions and multiplications - it makes no difference to peak performance but using shifts warms up faster and produces less compilation work.

Makes sense. I was thinking the compiler would do that statically anyway during compilation and multiplications and divisions are more readable. But I forgot that the lack of unsigned in Java makes this decision a bit less clear for the compiler, so it might delay until JIT (although I would rarely expect it to do that). In any case, I changed it now just to be on the safe side.

**Comment by lemire** [comment]
@larsk-db 

Note that unless the compiler can prove that the value is always positive, a division by 64 will never compile to a mere shift. You can check that it usually compiles to an arithmetic operation followed by a comparison and a branch or a conditional move, plus a shift. So it is massively more expensive (2x at least). So there is a real and lasting benefit to using `>>>6` in Java... sadly...

A multiplication by 64 is ok because there is no difference between that and a shift in most programming languages irrespective of the integer variable type.

**Comment by larsk-db** [comment]
Hmm, let me push some more edge case tests on this before merging. I think I found some issues (probably off-by-one) with completely full containers while benchmarking our use case against this API.

**Comment by simeonpilgrim** [comment]
It's interesting to read the explicit shift verse multiply, and the "don't assume the JIT will convert" because muls are used a lot in the NodeX code of the ART for the Roaring64Bitmap code. Does this implies these should be changed?

> @larsk-db
> 
> Note that unless the compiler can prove that the value is always positive, a division by 64 will never compile to a mere shift. You can check that it usually compiles to an arithmetic operation followed by a comparison and a branch or a conditional move, plus a shift. So it is massively more expensive (2x at least). So there is a real and lasting benefit to using `>>>6` in Java... sadly...
> 
> A multiplication by 64 is ok because there is no difference between that and a shift in most programming languages irrespective of the integer variable type.

**Comment by lemire** [comment]
@simeonpilgrim 

> muls are used a lot in the NodeX code of the ART for the Roaring64Bitmap code. Does this implies these should be changed?

You should point at the exact code so that we can discuss it, but note that a multiplication by a power of two *will* be optimized to a shift. Even the division by a power of two gets optimized, just not to a mere shift. So the code `i/64` is not *bad*. It is only slightly bad if it is likely to be called often.

So I am not recommending that you replace all multiplications and divisions by a power of two by the corresponding shift. Just be careful about the divisions by a power of two that are repeatedly called: you *may be leaving* some performance on the table. Even so, it is a micro-optimization: it will not double your performance. Maybe boost it by 5% to 10% in some cases.

We care about  5% to 10% but nobody gets fired for it.

**Comment by richardstartin** [comment]
Sorry I didn’t get round to looking at this further. I expect if there are any unanticipated problems it will be @larsk-db who is the first to find and fix them, so I don’t object to merging this.

**Comment by lemire** [comment]
@larsk-db Do you recommend merging at this time?

Note that I plan to issue a release shortly after...

**Comment by larsk-db** [comment]
> @larsk-db Do you recommend merging at this time?

Yup, I'm good with the current state.

**Pull request merged**
