### PR TITLE
Broken on jdk14

### PR DESCRIPTION
**Pull request by lemire**
Test for https://github.com/RoaringBitmap/RoaringBitmap/issues/388

### CODE REVIEW

**Comment by richardstartin** [comment]
That's gradle, it shades ASM so is not forward compatible. If you merge the upgrade to 6.3, this should go away.

**Comment by lemire** [comment]
@richardstartin Good to know.

**Comment by richardstartin** [comment]
Note that JDK12/JDK13 are effectively dead now.

**Comment by lemire** [comment]
Killing this in favour of @richardstartin's other PR.

**Pull request closed without merging**
