### PR TITLE
This should complete the fix for issue 333

### PR DESCRIPTION
**Pull request by lemire**
Should be self-explanatory.

### CODE REVIEW

**Comment by mdouaihy** [comment]
Bien vu! We didn't pay attention to this implementation.

**Comment by richardstartin** [comment]
@lemire  "offset" should not be a short, and this test will throw because of it, perhaps asserts in the containers that the ranges passed in make sense (e.g. the minimum is not negative) would help.

```java
  @Test
  public void intersectBitmapWithRangeHighBits() {
    Container[] values = new Container[1];
    RoaringArray ra = new RoaringArray(new short[1], values, 1);
    long[] bitmap = new long[1024];
    Arrays.fill(bitmap, 0, 512, 0xAAAAAAAAAAAAAAAAL);
    values[0] = new BitmapContainer(bitmap, 512 * Long.bitCount(0xAAAAAAAAAAAAAAAAL));
    RoaringBitmap rr1 = new RoaringBitmap(ra);
    Assert.assertFalse(rr1.intersects((1 << 15) , 0xFFFF));
  }
```

Could you fix it on this PR by changing

```java
short offset = Util.highbits(minimum);
```
to 
```java
int offset = (int)(minimum & 0xFFFF);
```

in both implementations?

**Comment by lemire** [comment]
@richardstartin I have added your test as well as extra tests.

**Comment by lemire** [comment]
I think this should be ok. Merging.

**Pull request merged**
