### PR TITLE
Fix add range around -1L in Roaring64NavigableMap and Roaring64Bitmap

### PR DESCRIPTION
**Pull request by blacelle**
### SUMMARY
- Multiple fixes related to Roaring64NavigableMap.addRange, specific to high being bigger than Long.MAX_VALUE
- Add tests to confirm same behavior between Roaring64NavigableMap and Roaring64Bitmap
- Add Roaring64NavigableMap.addRange, to prevent confusion between Roaring64NavigableMap.add(long, long) and Roaring64NavigableMap.add(long...). Same for Roaring64Bitmap

### Automated Checks

- [ ] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [ ] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by blacelle** [comment]
This is ready for review, hoping this will substantially stabilize the CI.

**Comment by blacelle** [comment]
@weijietong There is an equivalent bug in Roaring64Bitmap. I added a unit-test

**Comment by blacelle** [comment]
```

  @Test
  public void testRangeExtremeEnd() {
    Roaring64Bitmap x = newDefaultCtor();
    x.add(-3L, -1L);

    Assertions.assertEquals(2L, x.getLongCardinality());
    Assertions.assertArrayEquals(x.toArray(), new long[] {-3L, -2L});
  }
```
It loops infinitely adding Containers, until memory exhaustion.

**Comment by blacelle** [comment]
The rename .add into ,addRange was agreed in https://github.com/RoaringBitmap/RoaringBitmap/issues/507#issuecomment-898574260

**Comment by blacelle** [comment]
On a side-note, https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/test/java/org/roaringbitmap/TestAdversarialInputs.java#L20 seems to wrongly hardcode `i` into `3`. Fixing it leads to failing tests. @lemire

**Comment by blacelle** [comment]
@lemire Should .addRange be ported into RoaringBitmap? (as replacement for .add(long, long), as done in 64b implementation to prevent confusion with .add(long...)). If yes, I would not deprecate it into RoaringBitmap (as there is no danger in this case)

**Review by lemire — APPROVED** [review]
Excellent work. Looks fine to me.

**Comment by blacelle** [comment]
@lemire Should I merge when I confirm I'm fine, or should we wait for more reviews?

**Pull request merged**
