### PR TITLE
Fixing ArrayIndexOutOfBoundsException in andNotCardinality method

### PR DESCRIPTION
**Pull request by shencangsheng**
### SUMMARY

While working on the set operation functionality, I encountered an ArrayIndexOutOfBoundsException when using the andNotCardinality method to obtain the result. Upon investigating the source code, I discovered a potential logic flaw that could lead to an array index out of bounds. Unfortunately, I was unable to replicate this issue with other simple parameters, and I could only reproduce it by pasting the actual data that triggered the error.

Interestingly, the same data did not cause this exception when used with andNot().getCardinality().

env:
- openjdk 11
- RoaringBitmap: 0.9.46

```java
import org.roaringbitmap.RoaringBitmap;

public class Main {
    public static void main(String[] args) {
        RoaringBitmap s1 = RoaringBitmap.bitmapOf(-1388308580, 236217409, -805382570, 612285977, 1389629939, 851442526, 375756307, 61533603, 1908301308, 2097309572, 204769050, 703198559, -545810986, 2090296816, -87319453, 158018332, -685188145, -566739002, -1446363859, -372441875, -957637004, -1144076256, -1248859542, -160225853, 14707613, 866274329, 1550526350, 877999004, -1784269953, 1274953255, 1490490469, -1340013077, 2067958239, 51232349, 2060711699, -1802459974, 2039829040, -2079650027, -278950425, 1145674649, 298101576, 1687655442, 1209489632, -762136131, 399832491, 1077638711, -635674559, -1643781464, -1067907341, 144525399, 651571848, 1893053071, -2058528151, 1592871441, 84583235, 374119809, -867104416, -1941224259, 787356209, 1972857336, -720703901, -1310021857, -1831922816, 181898740, 600942551, -1745822849, -856908487, 2060184086, -1217485514, -1680395029, 1539735915, 2042390564, -1539856946, 1824974207, 1695025297, 1908431629, -395090370, -1688185468, 570601902, -701368853, -1211735380, -825285093, 788089714, -857723909, 1400502194, 285106906, -1450842998, -2125215206, 1451519492, -1559357910, 1157633452, -387704829, 2036134025, 1051239778, -1542956455, 357879569, 1962230155, -1994777800, 672516512, 174507423, -299175291, 821891018, 1062886766, -1313955904, 1732661804, -767116537, 1352149580, 2001322279, 1698147357, 40451458, 996819026, 1904959950, 2058544757, 1514282221, 234242255, -1364505429, 1498471146, 1134429786, -918860049, 1430732385, 644983298, 793600316, -1726956640, -538511147, -1945670935, 291567421, 1033590420, -1831809482, 985031287, -773476240, 1724734191, -1364525376, 1208307142, -2126741265, -1851759120, 1083333467, 185208087, -375950074, 48210573, -843304856, -295266615, -843941360, -524390895, -102924717, 836117637, 683196001, -1824825594, -1470017798, -1554712054, 291236023, -907874606, 2068945326, -899352179, -1488751007, -449279886, -1085935420, -2094131785, -474243782, 1306756671, 1353254318, 86944198, 1148225154, 487252515, -229770314, -1484325603, 109043190, -252122045, 1431750974, 1667547537, -1775516477, -512978266, -216545450, -486550865, -1193721685, -1108677522, -628326149, -1568065979, -675571394);
        RoaringBitmap s2 = RoaringBitmap.bitmapOf(2060184086, 704452713, 1236293943, -178539376, 2037977331, -78910667, -587409880, 204769050, -854426111, 90628341, -1411939301, -927754519, -211274987, 998450197, -1515133464, -1652963250, 499001553, 383696025, -2019580769, 1583380373, -79264832, 1065614902, 1243463658, 424214238, 1124141647, 271662535, 1415634429, 1893053071, -1624960757, -1933550809, -1170233109, -542340662, -1681838238, 292656484, 1587781520, -1463647396, -124042559, -162307067, 1411905814, -1524651941, 1935844108, 1992426746, 422443777, 679395872, -764857187, -401706366, -2007177999, 1044794027, -1561188953, 1627034126, -401273669, -123973748, -694963705, 838892817, -1640102435, 852253834, -23120023, -2072644924, 1140820264, -550227319, -1692730465, 1491150291, 1607642920, -1015774573, -1801713682, -752796152, -439281693, -792361100, -188208805, 808883165, -1364525376, 896915854, -1672522244, -1718572341);
        RoaringBitmap s3 = RoaringBitmap.bitmapOf(-30718004, -1652963250, -762136131, -1552606582, -1933550809, -1230616126, 736584428, -2136360654, 1097548480, 192408815, -295266615);
        System.out.println(RoaringBitmap.andNotCardinality(RoaringBitmap.and(s1, s2), s3));
    }
}
```

which outputs:

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.roaringbitmap.RoaringArray.getKeyAtIndex(RoaringArray.java:768)
	at org.roaringbitmap.RoaringBitmap.andNotCardinality(RoaringBitmap.java:914)
	at Main.main(Main.java:16)
```

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by richardstartin** [comment]
Thanks for the fix. Since you have a reproducer could you add it as a test case?

**Comment by shencangsheng** [comment]
@richardstartin  Sure, I have submitted the corresponding test case. The test cases in the previous two commits were breaking the project's code style, so I have reverted them and resubmitted the changes.

**Comment by shencangsheng** [comment]
@richardstartin  Apologies for the inconvenience. In the previous test case submission, there was an error. I have addressed the issue and resubmitted the changes.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
