### PR TITLE
search and replace cardinality checks with emptiness checks

### PR DESCRIPTION
**Pull request by richardstartin**
#239

### CODE REVIEW

**Comment by richardstartin** [comment]
Sorry just realised this was being worked on already.

**Comment by lemire** [comment]
Ping @amitdesai03

**Comment by lemire** [comment]
@amitdesai03 Do you recommend we pull it?

**Comment by amitdesai03** [comment]
@richardstartin no worries, I didnt get time to go much far with it anyways.

**Comment by amitdesai03** [comment]
@lemire Bit unfamiliar here.

I did look at at line by line changes, but as part of recommending PR merger, do I need to run benchmarks? I believe CI takes care of sanity test.

**Comment by lemire** [comment]
It'd be odd if it made the code slower. Maybe we can assume that it is safe, performance-wise.

**Comment by amitdesai03** [comment]
@lemire absolutely, i dont belive it would have any -ve impact, i was just not familiar whats part of process we follow.

Please go ahead with merge. 
Tx @richardstartin

**Comment by lemire** [comment]
Merged as requested.

**Pull request merged**
