### PR TITLE
Port ornot

### LINKED ISSUE #394: orNot still not entirely consistent
Hey, sorry for being so annoying :D @richardstartin 

now `orNot` sometimes truncates and sometimes doesn't. Probably an inconsistency between different containers.

Code to reproduce:
```
RoaringBitmap one = new RoaringBitmap();
one.add(0);
one.add(10);

RoaringBitmap other = new RoaringBitmap();
<initialize other>

one.orNot(other, 7);
Assert.assertTrue(one.contains(10));
```
This fails or succeeds depending on how `other` is initialized:

 * Succeeds: No init at all (`other` is empty)
 * Fails: `other.add(2)` (single number)
 * Succeeds: `other.add(2L, 5L)` (range)
 * Fails: `other.add(3L, 5L)` (smaller range)
 * Succeeds: `other.add(1L, 10L); other.remove(2L, 10L);` (single number, but probably represented as a run)
  * Fails: `for (int i : Arrays.asList(0, 1, 2, 3, 4, 5, 6)) { other.add(i); }` (range added one-by-one)

### PR DESCRIPTION
**Pull request by richardstartin**
Makes the buffer package consistent. Should close #394.

### CODE REVIEW

**Comment by richardstartin** [comment]
LGTM complaining about 

```
[2020-04-12 19:18:24] [autobuild] Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find it.uniroma3.mat:extendedset:1.3.4.
```

**Comment by lemire** [comment]
I am not worried about LGTM.

**Comment by richardstartin** [comment]
@lemire shall we merge this?

**Comment by lemire** [comment]
Please do. I prefer if you personally merge it, and then ping me so I can do the release.

**Comment by richardstartin** [comment]
ok. ping :)

**Pull request merged**
