### PR TITLE
implementation of subset relations - https://github.com/RoaringBitmap…

### PR DESCRIPTION
**Pull request by openkappa**
…/RoaringBitmap/issues/143

I've ported the C code for the subset relations from CRoaring. I implemented this relation as a contains(RoaringBitmap) on RoaringBitmap, so that if A = {1, 2, 3} and B = {2} A.contains(B) would be true, whereas B.contains(A) would be false.

### CODE REVIEW

**Comment by lemire** [comment]
+1

**Comment by openkappa** [comment]
I found a transposition error in the last line of RoaringBitmap::contains my first commit. Is it better to rebase now?

**Comment by gssiyankai** [comment]
It does not really matter. You can leave it as such or rebase if you prefer.

**Comment by lemire** [comment]
@openkappa  LGTM.

**Pull request merged**
