### PR TITLE
Rangebitmap serde bug

### PR DESCRIPTION
**Pull request by richardstartin**
Another bug in `RangeBitmap` 😿

### CODE REVIEW

**Comment by lemire** [comment]
Let me guess... another release in the near future? :-)

**Comment by richardstartin** [comment]
@lemire if you could release one more time I think that should be it for a while, but if you could send me credentials privately so I can release myself I wouldn't need to bother you.

**Comment by lemire** [comment]
@richardstartin  Yes. I'll do the release right now.

For your convenience, I can give you my credentials but I would prefer not do it in clear text because then an adversary could hijack the project. Can we find a secured way to do so? Are you on telegram?

**Comment by richardstartin** [comment]
I have signal, I'll ping you

**Pull request merged**
