### PR TITLE
Enable running mvn release... over parent/pom.xml

### PR DESCRIPTION
**Pull request by blasd**

### CODE REVIEW

**Comment by blasd** [comment]
`mvn -DdryRun=true release:prepare -Darguments="-DskipTests"` seems to impact only the root pom.xml

`mvn -f parent/pom.xml -DdryRun=true release:prepare -Darguments="-DskipTests"` fails because parent/pom.xml lacks developerConnection

I add here what enable a full release through `mvn -f parent/pom.xml release:prepare -Darguments="-DskipTests"`. I did not succeed  configuring mvn so that `-f parent/pom.xml` is not necessary. Then, we may choose to move files (I would not keep -f parent/pom.xml it but I'm not the one doing releases).

**Comment by Kineolyan** [comment]
Do you really need that parent folder ? Cannot we instead do a classic maven project by moving RoaringBitmap actual source to a specific submodule, and leaving all other submodules where they are ?
For the release, we just have to mark all modules but the sources are ignored by deploy plugin.

Something like:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-deploy-plugin</artifactId>
	<version>2.7</version>
	<configuration>
		<skip>true</skip>
	</configuration>
</plugin>
```

**Comment by blasd** [comment]
@Kineolyan You are right. I proposed this way to prevent moving all sources. I'm not confortable with the need of `-f` in the release process.

Should I move the files as you suggested or do we wait for @lemire confirmation (even if he already confirmed he is OK with moving files)?

**Comment by Kineolyan** [comment]
If you have some free time, you can create one commit with this specific change of structure, and nothing else.
This way, if @lemire or anyone else come to disagree with the change, you can easily revert to the previous state.
As mentioned elsewhere - I don't remember if it was in an issue or another PR - git will normally be smart enough to apply the new layout. It requires manual operations when new files are added, but I don't think the cost is very high. Particularly as there are only 2 active PRs as we speak.

**Comment by blasd** [comment]
The `move-only` commit is https://github.com/RoaringBitmap/RoaringBitmap/pull/181/commits/bd7e39002ee0ae1ce6728433477a2c503ed26621

**Comment by lemire** [comment]
@blasd My impression is that moving the files is fine at this time.

**Comment by Kineolyan** [comment]
I only look at this one, but it seems that examples/run.sh is now broken, as it will the content of roaringbitmap/target. In the script, it results in changes from `../target/` to `../roaringbitmap/target/`.
I don't know how other scripts work. 
This _examples_ folder could be transform into another module as github kindly flatten directory when only one exists.

**Comment by lemire** [comment]
@Kineolyan Good point. If we break the script in the examples directory, we should correct it, but I would not hold the PR on that account. The examples are more pedagogical...

**Comment by lemire** [comment]
I have restarted the travis tests. They failed after 45 minutes.

The problem seems to be with the JMH tests. The regular tests are slow but that's just because we have a lot of them. The JMH real-data tests are ridiculously slow *not* because of the testing itself... the testing takes fractions of seconds... what is incredibly slow is the JMH setup phase. I think we could complete all the testing itself in under a minute, but it takes something like 30 minutes. The bulk of the running time is spent setting up the tests, whatever this means...  I am not sure why the setup is so ridiculously slow. JMH in general is a dog performance-wise. I'm not sure why, but I suspect that it does crazy stuff in the background that you might not expect.

c.c. @gssiyankai

**Comment by lemire** [comment]
They have been running for 38 minutes. I suspect that they will time out again.

I don't know what to make of this.

Again: it is not the tests themselves that take a long time.

**Comment by lemire** [comment]
I think we can merge the PR, but we are going to have a problem with the tests, as travis will fail.

I propose to wait a bit in case someone has a clever idea to speed up the tests. We need a 10x speed-up.

cc @gssiyankai

**Comment by lemire** [comment]
To verify that the JMH tests should run under a minute, do:

```
$ cd simplebenchmark/
$ ./run.sh
```

**Comment by gssiyankai** [comment]
At first sight, I would say that something went wrong in the pom refactoring: my first guess would be that the configuration of the surefire maven plugin changed for the jmh module... perhaps because it is now defined globally in the parent pom ??
I do not have time to dig deeper but this is the first thing I would investigate.

**Comment by lemire** [comment]
[Here are the reported duration of the JMH tests for the head of master according to travis](https://travis-ci.org/RoaringBitmap/RoaringBitmap/jobs/270010028):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 111.875 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Running org.roaringbitmap.realdata.RealDataBenchmarkReverseIterateTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 113.382 sec - in org.roaringbitmap.realdata.RealDataBenchmarkReverseIterateTest
Running org.roaringbitmap.realdata.RealDataBenchmarkWideAndNaiveTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 114.309 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideAndNaiveTest
Running org.roaringbitmap.realdata.RealDataBenchmarkIOrTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 24, Time elapsed: 24.306 sec - in org.roaringbitmap.realdata.RealDataBenchmarkIOrTest
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrPqTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 113.508 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrPqTest
Running org.roaringbitmap.realdata.RealDataBenchmarkAndNotTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 106.438 sec - in org.roaringbitmap.realdata.RealDataBenchmarkAndNotTest
Running org.roaringbitmap.realdata.RealDataBenchmarkForEachTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 117.21 sec - in org.roaringbitmap.realdata.RealDataBenchmarkForEachTest
Running org.roaringbitmap.realdata.RealDataBenchmarkXorTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 109.802 sec - in org.roaringbitmap.realdata.RealDataBenchmarkXorTest
Running org.roaringbitmap.realdata.RealDataBenchmarkOrTest
Tests run: 96, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 224.08 sec - in org.roaringbitmap.realdata.RealDataBenchmarkOrTest
Running org.roaringbitmap.realdata.RealDataBenchmarkIterateTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 70.505 sec - in org.roaringbitmap.realdata.RealDataBenchmarkIterateTest
Running org.roaringbitmap.realdata.RealDataBenchmarkAndTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.024 sec - in org.roaringbitmap.realdata.RealDataBenchmarkAndTest
```

[Here are the current timings for this PR](https://travis-ci.org/RoaringBitmap/RoaringBitmap/jobs/269975114):
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.roaringbitmap.realdata.RealDataBenchmarkAndNotTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 24, Time elapsed: 255.491 sec - in org.roaringbitmap.realdata.RealDataBenchmarkAndNotTest
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 295.253 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Running org.roaringbitmap.realdata.RealDataBenchmarkWideAndNaiveTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 282.686 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideAndNaiveTest
Running org.roaringbitmap.realdata.RealDataBenchmarkIterateTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 309.58 sec - in org.roaringbitmap.realdata.RealDataBenchmarkIterateTest
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrPqTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 288.686 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrPqTest
Running org.roaringbitmap.realdata.RealDataBenchmarkAndTest
Tests run: 144, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 283.195 sec - in org.roaringbitmap.realdata.RealDataBenchmarkAndTest
Running org.roaringbitmap.realdata.RealDataBenchmarkOrTest
```


So it definitively seems much slower.

Of course, it is also possible the travis architecture changed. So I am going to ask it to rerun the tests for the head of master. If they pass, then we have mystery on our hands in that this PR slows things down dramatically.

**Comment by lemire** [comment]
I think that the prudent thing to do is not to merge this PR until we can figure out the nature of the performance issue.

**Comment by Kineolyan** [comment]
I did test anything, but it seems that the gpg plugin is called for every sub module, while it was only applied to roaring bitmap code before. 
I don't know what it does, but it may be long for jhm module, which has a lot of classes and annotations and stuff

**Comment by blasd** [comment]
I agree about not to merge.

One way to manage the gpg plugin in the context of maven central publication is to add it the related plugins in a profile dedicated to the release process. However it is not the way the original pom was configured as it rather relies on `-Dgpg.skip=true`.

http://www.sonatype.org/nexus/2014/10/08/distribute-project-artifacts-in-maven-central-with-nexus-oss/

About performance tests, I kept the surefire config for each module. I'll dig deeper

**Comment by lemire** [comment]
We can certainly move the gpg stuff, and that might be good for other reasons, but are the jars getting signed in the first place?

What happens if you type 

```
$ for file in $( find ./ -name "*.jar" ) ; do echo $file; jarsigner -verify $file; done
```

**Comment by lemire** [comment]
I restarted the tests on the current head of master and they run within the accepted time limit. So it is strong evidence that this PR slows down the duration of the tests, for some mysterious reason.

**Comment by blasd** [comment]
The number of tests for RealDataBenchmarkAndNotTest grows from 48 to 144 :S

Is it possible the realdataset changed, being much bigger ? The pom in master refers to realdataset 0.6.30. I've changed it to refers to current pom: 0.6.52-SNAPSHOT

In master:
>
        <dependency>
            <groupId>org.roaringbitmap</groupId>
            <artifactId>real-roaring-dataset</artifactId>
            <version>0.6.30-SNAPSHOT</version>
        </dependency>

**Comment by lemire** [comment]
hmmm...

**Comment by lemire** [comment]
Ah. Yes. It now runs each test 3 times. The dataset is the same, but JMH repeats the same tests.

**Comment by lemire** [comment]
Ok. So here are the tests being run...

```
Running org.roaringbitmap.realdata.RealDataBenchmarkAndNotTest
testing: roaring census-income false [0.023 s]
testing: roaring census-income true [0.043 s]
testing: roaring_with_run census-income false [0.017 s]
testing: roaring_with_run census-income true [0.029 s]
testing: roaring census1881 false [0.002 s]
testing: roaring census1881 true [0.003 s]
testing: roaring_with_run census1881 false [0.003 s]
testing: roaring_with_run census1881 true [0.004 s]
testing: roaring dimension_008 false [0.004 s]
testing: roaring dimension_008 true [0.012 s]
testing: roaring_with_run dimension_008 false [0.006 s]
testing: roaring_with_run dimension_008 true [0.012 s]
testing: roaring dimension_003 false [0.006 s]
testing: roaring dimension_003 true [0.071 s]
testing: roaring_with_run dimension_003 false [0.003 s]
testing: roaring_with_run dimension_003 true [0.018 s]
testing: roaring dimension_033 false [0.003 s]
testing: roaring dimension_033 true [0.005 s]
testing: roaring_with_run dimension_033 false [0.001 s]
testing: roaring_with_run dimension_033 true [0.001 s]
testing: roaring uscensus2000 false [0.0 s]
testing: roaring uscensus2000 true [0.001 s]
testing: roaring_with_run uscensus2000 false [0.0 s]
testing: roaring_with_run uscensus2000 true [0.0 s]
testing: roaring weather_sept_85 false [0.016 s]
testing: roaring weather_sept_85 true [0.039 s]
testing: roaring_with_run weather_sept_85 false [0.019 s]
testing: roaring_with_run weather_sept_85 true [0.026 s]
testing: roaring wikileaks-noquotes false [0.001 s]
testing: roaring wikileaks-noquotes true [0.003 s]
testing: roaring_with_run wikileaks-noquotes false [0.001 s]
testing: roaring_with_run wikileaks-noquotes true [0.001 s]
testing: roaring census-income_srt false [0.002 s]
testing: roaring census-income_srt true [0.003 s]
testing: roaring_with_run census-income_srt false [0.004 s]
testing: roaring_with_run census-income_srt true [0.006 s]
testing: roaring census1881_srt false [0.0 s]
testing: roaring census1881_srt true [0.001 s]
testing: roaring_with_run census1881_srt false [0.0 s]
testing: roaring_with_run census1881_srt true [0.0 s]
testing: roaring weather_sept_85_srt false [0.005 s]
testing: roaring weather_sept_85_srt true [0.008 s]
testing: roaring_with_run weather_sept_85_srt false [0.004 s]
testing: roaring_with_run weather_sept_85_srt true [0.005 s]
testing: roaring wikileaks-noquotes_srt false [0.001 s]
testing: roaring wikileaks-noquotes_srt true [0.001 s]
testing: roaring_with_run wikileaks-noquotes_srt false [0.0 s]
testing: roaring_with_run wikileaks-noquotes_srt true [0.001 s]
```

I draw your attention to the fact that each test takes much less than one second. So this should complete in about a second. The bulk of the time is spent in JMH preparing the test.

**Comment by lemire** [comment]
I might have found the issue.

**Comment by lemire** [comment]
Ok. So the problem has to do with accessing the string data within the zip files found in real-roaring-dataset/src/main/resources/real-roaring-dataset when going through JMH. If you just write a simple java program to access it, it is fine, but if you go through JMH, there is something funny happening.

**Comment by lemire** [comment]
@blasd  

I recommend dropping the JMH unit tests. Our JMH module has a performance bug that makes it unbearable.

I have opened an issue : https://github.com/RoaringBitmap/RoaringBitmap/issues/182

It will temporarily weaken our testing framework, but I think it is best we can do for now.

It might be simpler to discard the JMH module and write our own benchmarking framework. JMH is just very, very slow. It is probably better suited for tiny microbenchmarks.

**Comment by lemire** [comment]
@blasd 

To be clear, I recommend simply editing your travis file so that the JMH tests are omitted.

**Comment by blasd** [comment]
2 things: I modified JMH tests so that Immutable/Buffer tests does not require writing everything in a tmp file. I felt the goal is to check the implementation relying on a ByteBuffer, not caring if it be a heap wrapper or a file.

I also fixed the travis script step: the 3rd step run test on the root pon: it led to run test on all module: no big deal, except for JMH as we were lacking the `-DBITMAP_TYPES=ROARING_ONLY` switch: I restricted the first step for RoaringBitmap tests, and kept the last step for JMH test (restricted to JMH only)

**Comment by blasd** [comment]
>
Running org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.356 sec - in org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaiveTest

It sounds quite good for final build timing!

**Comment by lemire** [comment]
Great. I think you got it fast enough.

**Pull request merged**
