### PR TITLE
Prevent creating temp containers

### PR DESCRIPTION
**Pull request by amitdesai03**
https://github.com/RoaringBitmap/RoaringBitmap/issues/185
https://github.com/RoaringBitmap/RoaringBitmap/issues/239

### CODE REVIEW

**Comment by lemire** [comment]
I think that we do not store empty containers, so this condition will always be true. No?

**Comment by lemire** [comment]
> I though we never confiscate empty containers on remove() call. So there is possibility.

That would be a bug. I don't think we do so... 

```
  public void remove(final int x) {
    final short hb = Util.highbits(x);
    final int i = highLowContainer.getIndex(hb);
    if (i < 0) {
      return;
    }
    highLowContainer.setContainerAtIndex(i,
        highLowContainer.getContainerAtIndex(i).remove(Util.lowbits(x)));
    if (highLowContainer.getContainerAtIndex(i).isEmpty()) {
      highLowContainer.removeAtIndex(i);
    }
  }
```

**Comment by lemire** [comment]
> Also, would you be open to have gitter/irc channel for more agile communication?

We have a [mailing list as you know](https://groups.google.com/forum/#!forum/roaring-bitmaps).

We can create more channels. If someone organizes a chat channel, we will be sure to add links to it.

**Comment by lemire** [comment]
> Did you mean we modify internals of and() methods to prevent allocating anything till something found to intersect?

That's what I meant, yes. See my description:

_There are clever tricks we could use to start scanning the input containers, advance up to the point where there might be values to be intersected, and bail out without generating an empty container if the intersection is empty._

I am thinking that instead of eagerly allocating a new container, we could delay the allocation until we we know the result won't be empty. I'd start with array-array intersections.

**Comment by richardstartin** [comment]
I’d be tempted to verify the container isn’t scalarised before optimising this. If you get a significantly worse result and different allocation rates from -prof gc when disabling escape analysis when executing this section of code, it’s being optimised for you.

**Comment by lemire** [comment]
> I’d be tempted to verify the container isn’t scalarised before optimising this. If you get a significantly worse result and different allocation rates from -prof gc when disabling escape analysis when executing this section of code, it’s being optimised for you.

That's a very good point. I'll recopy your comment as part of the main issue.

**Comment by lemire** [comment]
I will close this for now.

**Pull request closed without merging**
