### PR TITLE
Checkstyle fixes

### PR DESCRIPTION
**Pull request by okrische**
Hey,

can someone please verify, if the current master branch can not be built because of checkstyle violations? Because here it does:

``
$ mvn clean package -DskipTests -Dgpg.skip=true
`` 

It does so on do/while blocks, when the "while" statement is put on the same line as the curly bracket.

If this is wanted, then i fixed those violations.

I also added checks for "run.sh" in the jmh folder, so that it fails, whenever one of the "mvn" commands fails. Right now it always ran through and jmh used old deployed versions of the jars (grrrr, took me some time to figure out, that it failed bcs of checkstyle)

### CODE REVIEW

**Comment by okrische** [comment]
Checkstyle also fails, when compiled/run with jdk7, hmm.

``
$ mvn clean checkstyle:checkstyle 
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle (default-cli) on project RoaringBitmap: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/AuditListener : Unsupported major.minor version 52.0
...
``

Looks like, checkstyle already works with jdk8? Sigh.

**Comment by gssiyankai** [comment]
Hi @okrische,
The build is failing because:
- Roaring depends on the latest version of com.puppycrawl.tools:checkstyle
- com.puppycrawl.tools:checkstyle:0.7 has been released 2 weeks ago
- this version is not compatible with java 7

To fix the issue, just set explicitly the version to 6.19 in the root pom.

HTH

**Comment by okrische** [comment]
So, with 7.0 then, the RightCurly check will fail with the current master. Ok. Do you think, the RightCurly changes make sense nonetheless? 

I am pretty used to this:

``
do {
   something();
} while(test());
``

But with 7.0 of the puppy checkstyle thingie, together with google style, it enforces:

``
do {
   something();
} 
while(test());
``

**Comment by lemire** [comment]
@okrische 

I am with you here... this style rule seems a tad odd. Nothing wrong with it per se, but forcing people to write this way is a bit much.

What are your thoughts @gssiyankai ?

**Comment by okrische** [comment]
Maybe the google style guide has not been updated yet on checkstyle side, yet.

- https://google.github.io/styleguide/javaguide.html#s4.1-braces

> Line break after the closing brace, only if that brace terminates a statement or terminates the body of a method, constructor, or named class. For example, there is no line break after the brace if it is followed by else or a comma.

And in a do/while the do {} is followed by "while". Hm.

**Comment by gssiyankai** [comment]
@lemire,
 No preference. I can go with both.

**Comment by lemire** [comment]
@okrische  

I feel strongly that this is correct:

```java
        do {
            System.out.println("Count is: " + count);
            count++;
        } while (count < 11);
```

while this is ugly...

```java
        do {
            System.out.println("Count is: " + count);
            count++;
        } 
        while (count < 11);
```

If someone feels very differently, we can discuss it... but if not...

> Maybe the google style guide has not been updated on checkstyle side, yet.

We do this work actually. Roaring has its own style which is a watered down version of the Google style as interpreted by checkstyle... (meaning, we allow more things) That is, we do not use the default "google style" from checkstyle, instead we provide our own.  This gives us some flexibility.

Can you go to file ``style/roaring_google_checks.xml``? Find ``<module name="RightCurly">``... next look at the content:

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/style/roaring_google_checks.xml#L60

I think that the problem is that we have ``LITERAL_DO`` in the list which forces you to make the changes from your commit...

https://github.com/RoaringBitmap/RoaringBitmap/pull/111/commits/f3617a045e90f4ad59c1722d3233e18f1e7834ee

I think that if you delete LITERAL_DO from the line 60 in ``style/roaring_google_checks.xml``, you'll find that your "ugly" commit is unnecessary.

Can you check?

(Note: I do not mean to imply that you did ugly work. Quite the opposite. You brought forth an important issue.)

**Comment by okrische** [comment]
* changed roaring_google_checks.xml, 
* set version of puppycrawl checkstyle tool to 6.19, 
* (also tested with puppycrawl checkstyle tool 7.0, so, when roaring goes jdk8, then it will work as well)
* and added that fix to run.sh in jmh, so it will fail, when any build fails

**Comment by lemire** [comment]
Looks great to me. Since @gssiyankai  went over some of this... let us merge.

**Pull request merged**
