### PR TITLE
Evaluate batch iteration

### PR DESCRIPTION
**Pull request by richardstartin**
I have implemented a similar pattern to the go library for batch iteration. I will probably port this to the buffer package later this week. I would be interested in seeing benchmark results for this implementation.

### CODE REVIEW

**Comment by richardstartin** [comment]
OK. I plan to port to the buffer version and have used the wrong email address on some commits which needs fixing (I will need to force push).

**Comment by lemire** [comment]
@richardstartin I think we want to do something meaningful like sum the values being iterated over. And compare the old-school iterators with the new iterators.

Is this what you have in mind?

**Comment by richardstartin** [comment]
@lemire The code I propose evaluating is on #243 - can we discuss there?

**Comment by lemire** [comment]
Of course.

**Comment by lemire** [comment]
I'm going to lock this conversation.

**Pull request closed without merging**
