### PR TITLE
bit slice index for java

### PR DESCRIPTION
**Pull request by Smallhi**

### CODE REVIEW

**Comment by lemire** [comment]
@Smallhi Can you check the javadoc warnings that your PR causes ? https://lgtm.com/projects/g/RoaringBitmap/RoaringBitmap/rev/pr-90e0baf8d04e72cf52df59d723bf043787268863

**Comment by Smallhi** [comment]
> @Smallhi Can you check the javadoc warnings that your PR causes ? https://lgtm.com/projects/g/RoaringBitmap/RoaringBitmap/rev/pr-90e0baf8d04e72cf52df59d723bf043787268863

Ok,I’ll check and fix these

**Comment by Smallhi** [comment]
@lemire  I made some mistakes of git commit infos..... could u close this pr, I want commit a new one ....

**Comment by lemire** [comment]
@Smallhi I will do so.

Please run 

```
./gradlew checkstyleMain
```

**Pull request closed without merging**
