### PR TITLE
real iand between run and array container

### PR DESCRIPTION
**Pull request by xtonik**
### SUMMARY
Routine `iand()` between run and array container reworked to be done in place.

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by lemire** [comment]
I am not sure that this is better. It could perform worse in practice. The problem is that this implementation does not make sure of the fact that the array is sorted.

**Comment by lemire** [comment]
Fantastic.

**Comment by lemire** [comment]
@xtonik Can you extend to MappableArrayContainer.java?

See:

https://github.com/RoaringBitmap/RoaringBitmap/blob/23a855bf2c1d31d6e29143c699a8219a17ca0d75/RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java#L686

**Comment by xtonik** [comment]
The same story with omitted equivalent code somewhere else. I will look at this.

**Comment by xtonik** [comment]
Done.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
