### PR TITLE
BSI as a distinct jar file

### PR DESCRIPTION
**Pull request by lemire**
### SUMMARY

This is meant to allow us to release BSI as a distinct jar since some users are concerned with code bloat. The new BSI artefact weights in at about 5% of the total RoaringBitmap jar.

```
❯ ls -alh ./bsi/build/libs/bsi-0.9.11-SNAPSHOT.jar
-rw-r--r--  1 lemire  staff    27K 14 Jun 10:22 ./bsi/build/libs/bsi-0.9.11-SNAPSHOT.jar
```

```
❯ ls -alh ./RoaringBitmap/build/libs/RoaringBitmap-0.9.11-SNAPSHOT.jar 
-rw-r--r--  1 lemire  staff   401K 14 Jun 10:22 ./RoaringBitmap/build/libs/RoaringBitmap-0.9.11-SNAPSHOT.jar
```

### Automated Checks

- [X] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [X] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Review by richardstartin — COMMENTED** [review]
Most of this diff seems unrelated to the goal of splitting the feature out

**Comment by lemire** [comment]
@richardstartin You are quick correct. What happened there...?

**Comment by lemire** [comment]
Here are my commits...

https://github.com/RoaringBitmap/RoaringBitmap/pull/496/commits/664e2a56db2e5c92597e76dd020605809ec8f555

https://github.com/RoaringBitmap/RoaringBitmap/pull/496/commits/664e2a56db2e5c92597e76dd020605809ec8f555

They look clean enough. I wonder where the rest of the changes come from.

**Comment by lemire** [comment]
@richardstartin Ah. Ok. Just did a rebase. It should look better now.

**Review by richardstartin — APPROVED** [review]
LGTM

**Comment by lemire** [comment]
I'll merge and *try* to issue a release.

**Comment by lemire** [comment]
Amazingly, it looks like the release went through!!!

**Pull request merged**
