### PR TITLE
serialize to bytebuffer

### PR DESCRIPTION
**Pull request by richardstartin**

### CODE REVIEW

**Comment by lemire** [comment]
This solves https://github.com/RoaringBitmap/RoaringBitmap/issues/322

**Comment by lemire** [comment]
Looks like great work to me. Thorough.

**Comment by richardstartin** [comment]
Thanks. I haven't benchmarked it but I'm sure this will soften the CPU spikes I see during serialisation of many sparse bitmaps so I am keen to pick up the next release. Please ping me when you get time to issue a release.

**Comment by lemire** [comment]
@richardstartin 

Working on it right now. I just want to update the documentation before I issue a release.

Even if the performance was the same, the usage is now so much nicer...

**Comment by lemire** [comment]
I have release 0.8.0. I want with a new minor version because I think we have a much better API.

**Comment by richardstartin** [comment]
I notice that Spark may be [picking up 0.7.45 for Kryo serialisation](https://github.com/apache/spark/pull/24264). It may be worth their while to use `ByteBuffer` in preference to `DataOutput`.

**Comment by richardstartin** [comment]
I can't share more details but this reduced a "CPU utilisation" spike from 50% to under 15%. It was a big efficiency gain.

**Comment by lemire** [comment]
@richardstartin 

I fear that this long lasting inefficiency is largely my fault. I was assuming that if there were any performance differences with such functions, it would be small. I held to my assumption for too long without checking.

**Pull request merged**
