### PR TITLE
Fix 377

### PR DESCRIPTION
**Pull request by lemire**
Complete https://github.com/RoaringBitmap/RoaringBitmap/pull/380

@richardstartin : the fancy parametrized class was slowing down tests... making it lengthy to test just one function... I am also not sure what value this has given that simpler code just appears to achieve the same result, more efficiently...

### CODE REVIEW

**Comment by richardstartin** [comment]
How do you know which test case breaks if you have a regression, and how do you run just that test? These considerations are why you don’t typically have multiple unrelated assertions per test case. And what is the difference in performance?

**Comment by richardstartin** [comment]
I doubt that it is JUnit is responsible for the slowness you report, but Gradle IDE integration.  Running with Gradle in "Settings > Build, Execution, Deployment > Gradle > Build and run using", the first run took 17 seconds and the second took 3 seconds (the daemon was already running the second time).

Changing to IDEA, I ran all the tests in well under a second the first time and every time even after restarting the IDE.

I think that bundling test cases into a single test for performance reasons is a bad move.

**Comment by richardstartin** [comment]
Gradle
image

**Comment by lemire** [comment]
I will split the issues and the PR. Just a minute.

**Comment by lemire** [comment]
I'll merge. I will address the performance issues separately.

**Comment by lemire** [comment]
> I doubt that it is JUnit is responsible for the slowness you report, but Gradle IDE integration. 

I run the tests directly with gradle commands. I don't go through an IDE in this instance.

I wanted to document precisely how one can run just one test using gradle alone... and I found that it was atrociously slow.

**Comment by lemire** [comment]
> How do you know which test case breaks if you have a regression, and how do you run just that test? 

Well. Can you give me the gradle command line to run just one test... I will tell you how long it takes... Can we agree that if it takes more than a minute, then it is broken?

**Pull request merged**
