### PR TITLE
fix boundary bugs, add test for floating point use case

### PR DESCRIPTION
**Pull request by richardstartin**
Fixes some bugs (one by specification) around very large values, and adds a test case for encoded floating point numbers.

### CODE REVIEW

**Comment by richardstartin** [comment]
Surprising: 

```

```#
64
# A fatal error has been detected by the Java Runtime Environment:
65
#
66
#  SIGSEGV (0xb) at pc=0x00007fd238a16425, pid=1840, tid=1868
67
#
68
# JRE version: OpenJDK Runtime Environment Zulu11.50+19-CA (11.0.12+7) (build 11.0.12+7-LTS)
69
# Java VM: OpenJDK 64-Bit Server VM Zulu11.50+19-CA (11.0.12+7-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
70
# Problematic frame:
71
# J 11414 c2 org.roaringbitmap.RunContainer.or(Lorg/roaringbitmap/RunContainer;)Lorg/roaringbitmap/Container; (333 bytes) @ 0x00007fd238a16425 [0x00007fd238a15900+0x0000000000000b25]
72
#
73
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/core.1840)
74
#
75
# An error report file with more information is saved as:
76
# /home/runner/work/RoaringBitmap/RoaringBitmap/RoaringBitmap/hs_err_pid1840.log
77
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
78
#
79
# If you would like to submit a bug report, please visit:
80
#   http://www.azul.com/support/
81
#

**Comment by lemire** [comment]
Rerunning CI tests.

**Comment by richardstartin** [comment]
Sorry for overloading you with requests, could you do another release when you get some time to do it please?

**Comment by lemire** [comment]
@richardstartin No burden at all.

Note that I do not create releases eagerly by design. So while it is a bit annoying, I want you to really ask for a release. Eager releases can create more trouble.

(I would also gladly give you the credentials if you want the ability to initiate the release, though I do not mind doing it.)

**Comment by lemire** [comment]
On the plus side, we no longer have a shitty process that takes 30 minutes.

**Comment by lemire** [comment]
The release is done.

**Pull request merged**
