### PR TITLE
Xor instead of subtraction

### PR DESCRIPTION
**Pull request by xtonik**
It is more performant to use XOR operation instead of subtraction using identity $`2^n - 1 - x = (2^n - 1) \oplus x`$ for $`x < 2^n`$.

### CODE REVIEW

**Comment by richardstartin** [comment]
I'd want to be sure the JIT compiler doesn't know this identity by taking a look at the disassembly before and after for at least one of these changes. Does this make a measurable difference?

**Comment by lemire** [comment]
> I'd want to be sure the JIT compiler doesn't know this identity by taking a look at the disassembly before and after for at least one of these changes. 

The compiler needs to know that the x is smaller than 2^n, and then it needs to decide to do the optimization.

> Does this make a measurable difference?

Well. I would be quite surprised if this optimization made a measurable difference.

Recent processors can retire 4 additions per cycle.

I don't want to be prematurely negative, but we are unlikely to be performance bounded by addition operations.

**Comment by richardstartin** [comment]
> The compiler needs to know that the x is smaller than 2^n, and then it needs to decide to do the optimization.

but it's easy enough to check

**Comment by lemire** [comment]
LLVM does it...

Capture d’écran, le 2023-07-12 à 13 57 48

**Comment by lemire** [comment]
I am skeptical that this is faster so I am not going to merge right away. I am concerned that it may make the code harder to read with no benefit.

**Pull request closed without merging**
