### PR TITLE
Methods for replacing children for Node various type optimized

### PR DESCRIPTION
**Pull request by xtonik**
### SUMMARY
Methods for replacing children for Node of various type optimized. Am I missing something that according to the issue, the code in `Node4` and `Node16` was completely useless?

Small benchmark for comparison included in [Node48Test.java](https://github.com/RoaringBitmap/RoaringBitmap/compare/master...xtonik:RoaringBitmap:REPLACE_CHILDREN_OPTIMIZED?expand=1#diff-6ce2b8e13a9c62ca552cca301b1a446a1975975c00149089b7d616a718da879e). It is run as test for simplicity, but it outperforms original implementation several times, so this is sufficient for this purpose. It should be removed before merge.

### Automated Checks

- [x] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [x] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by lemire** [comment]
Looks good to me. I encourage to finish this PR. We should be able to merge.

**Comment by xtonik** [comment]
Please wait with merging until I will remove temporary comparison benchmark.

**Comment by xtonik** [comment]
I removed temporary benchmark, PR can be merged.

**Comment by lemire** [comment]
Merged.

**Pull request merged**
