### PR TITLE
Improve exception message, add unit-test for #528

### PR DESCRIPTION
**Pull request by blacelle**
### SUMMARY
- Relates to https://github.com/RoaringBitmap/RoaringBitmap/issues/528
- Improve exception message 
- Add unit-test to explicit the unsupported behavior.

### Automated Checks

- [ ] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [ ] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by blacelle** [comment]
> Of course, this will hit us at several places, not just with and... won't it?

The issue would occur on .and, .andNot, .naivelazyor, or.

I see (very old) comments like:

      // TODO Reviewers: is it a good idea to rely on BitmapDataProvider except in methods
      // expecting an actual MutableRoaringBitmap?

> I am genuinely curious... why do we need MutableRoaringBitmap in the first place?

Roaring64NavigableMap can be initialized with either RoaringBitmap or MutableRoaringBitmap. However, booleanLogic operations are not available over Roaring64NavigableMap based on different BitmapDataProvider implementations.

We could soften this by relying on .toRoaringBitmap().

However, the cause of the spotted issue is that in one case, I create an empty MutableRoaringBitmap, instead of relying on the proper BitmapDataProvider implementation.

**Comment by lemire** [comment]
@blacelle I have minor comments you may want to look at.

**Comment by blacelle** [comment]
Some runs are OK while just changing the test log configuration. Let see if the latest run with a relevant test log configuration is OK.

**Comment by blacelle** [comment]
https://pipelines.actions.githubusercontent.com/5l8uprPpPsJHAGAlp4HJI7NrJ6ZaEr1ieYD948ooQMEnFeIvqj/_apis/pipelines/1/runs/2288/signedlogcontent/2?urlExpires=2021-10-08T09%3A59%3A26.3169687Z&urlSigningMethod=HMACV1&urlSignature=fBfcVNvB%2Bp2WDYqZulw7ReYoxAhP0kbT0jZHQtTbiJs%3D

```
2021-10-08T09:45:21.8924100Z FAILURE: Build failed with an exception.
2021-10-08T09:45:21.8924609Z 
2021-10-08T09:45:21.8925130Z * What went wrong:
2021-10-08T09:45:21.8925665Z Java heap space
```

**Comment by richardstartin** [comment]
I don't think further changes to parallel aggregation are necessary here; it's never failed before and it may be a symptom rather than a cause. There's a range of tests optimisations (e.g. not printing large strings even if they are sent to /dev/null) which could be done in another PR.

**Comment by lemire** [comment]
Merged.

**Pull request merged**
