### PR TITLE
squid:S1066 - Collapsible "if" statements should be merged

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrence of Sonar rule
squid:S1066 - Collapsible "if" statements should be merged.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1066
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by lemire** [comment]
@gssiyankai 

You want to check it out?

**Comment by gssiyankai** [comment]
@lemire 
I am not in favor of enforcing this Sonar rule. I agree that it sometimes increases code readability. But sometimes it does not.
What do you think ?

**Comment by lemire** [comment]
@gssiyankai  Indeed, in this instance, when I look at the code after and before, it is not obvious that the after code is more readable.

**Comment by lemire** [comment]
@georgekankava 

I think we are unconvinced by this particular PR. Do you have any arguments?

**Comment by georgekankava** [comment]
No if you don't prefer this rule it is up to you.

**Comment by lemire** [comment]
@georgekankava  I think we appreciate very much you work, but I am going to close this particular PR without merging as the benefits are unclear.

**Pull request closed without merging**
