### PR TITLE
ImmutableRoaringArray construction micro-optimisations

### PR DESCRIPTION
**Pull request by richardstartin**
This showed up in a profile querying inverted indexes in pinot, not a lot can be done about this but this PR makes some small improvements.

### CODE REVIEW

**Review by lemire — APPROVED** [review]
The bulk of this change has to do with reducing the calls to this function...

```
public boolean hasRunCompression() {
    return (buffer.getInt(0) & 0xFFFF) == SERIAL_COOKIE;
  }
```

In theory, it could be very fast, and even optimized away, but, evidently, it can also have a measurable cost.

The revised code is somewhat harder to use and to read, so there is a trade-off, but the trade-off seems minimal.

I recommend moving forward *if* the author has determined that there are actual gains. (If this is a speculative optimization, I would hold on.)

**Comment by richardstartin** [comment]
The idea is to keep the flag on the stack and avoid jumping around the buffer, it also allows some constant folding. Let me get some numbers.

**Comment by lemire** [comment]
To be clear: I see full well why it is an optimization. :-)

**Comment by richardstartin** [comment]
This is about 25% faster in a microbenchmark:


```
Benchmark                     Mode  Cnt   Score   Error  Units
MapBitmapBenchmark.construct  avgt   25  23.531 ± 0.371  ns/op

Benchmark                     Mode  Cnt   Score   Error  Units
MapBitmapBenchmark.construct  avgt   25  17.404 ± 0.090  ns/op
```

```java
@State(Scope.Benchmark)
public class MapBitmapBenchmark {

  private ByteBuffer buffer;

  @Setup(Level.Trial)
  public void setup() throws IOException {
    File file = new File(Files.createTempDir(), "bitmap");
    file.deleteOnExit();
    try (RandomAccessFile raf = new RandomAccessFile(file, "rw")) {
      RoaringBitmap bitmap = RandomData.randomBitmap(0x10000, 0.2, 0.2);
      buffer = raf.getChannel().map(READ_WRITE, 0, bitmap.serializedSizeInBytes())
          .order(ByteOrder.LITTLE_ENDIAN);
      bitmap.serialize(buffer);
      buffer.flip();
    }
  }


  @Benchmark
  public ImmutableRoaringBitmap construct() {
    return new ImmutableRoaringBitmap(buffer);
  }
}
```

@lemire - up to you, do you think it's worth it for the increased complexity which concerns you?

**Comment by lemire** [comment]
@richardstartin Let us merge. I did not mean to be critical of your code. It is slightly less automated but it is still perfectly maintainable.

**Pull request merged**
