### PR TITLE
fix the difference of the map in java and c when save to clickhouse.

### PR DESCRIPTION
**Pull request by panda0120**
fix the difference of the map in java and c when save to clickhouse.

https://github.com/RoaringBitmap/RoaringBitmap/issues/366

the test jdbc driver is:
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2-patch11</version>
        </dependency>

### CODE REVIEW

**Comment by lemire** [comment]
@panda0120 This PR seems acceptable, but do you have tests to validate the change?

**Comment by panda0120** [comment]
no, wait, let me think it over.

**Comment by lemire** [comment]
Closing in favor of https://github.com/RoaringBitmap/RoaringBitmap/pull/598

**Comment by learn2Pro** [comment]
> fix the difference of the map in java and c when save to clickhouse.
> 
> #366
> 
> the test jdbc driver is: com.clickhouse clickhouse-jdbc 0.3.2-patch11

did this change published?

**Comment by lemire** [comment]
The current PR (572) has been discarded. I do not think that it was ever correct.

**Pull request closed without merging**
