### PR TITLE
Issue#426 Add stream() and reverseStream() methods that provide Int/LongStream() for streaming the index of set bits in Roaring(64)Bitmaps. (#427)

### PR DESCRIPTION
**Pull request by lemire**
This is a copy of  @JervenBolleman PR.

Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/426

### CODE REVIEW

**Comment by lemire** [comment]
Ah. Now we are getting the tests.

**Comment by lemire** [comment]
@JervenBolleman  You like really long lines!!! :-)

We have style checkers in place and we forbid overly long lines.

**Comment by lemire** [comment]
Now we are good. Merging.

**Comment by JervenBolleman** [comment]
@lemire thanks for fixing the long lines. I only saw the line length requirements after making the pull request and did not have time yet to fix it myself. I really depend on the autoformatter of eclipse in my day job to avoid this, but used netbeans to do this patch.

**Pull request merged**
