### PR TITLE
Add cached cardinality

### PR DESCRIPTION
**Pull request by incaseoftrouble**
I'm using RoaringBitmaps in a project where I have a lot of calls to `RoaringBitmap#contains(RoaringBitmap)`. Calls typically are `largeSet.contains(smallSet)`. Profiling shows that ~85% (!) of the `contains(...)` call is spent in `getCardinality()`. Adding caching drops this to 0%.

Tests (`gradlew check`) complete successfully. The cached value is exhaustively checked via an assert, comparing it to the eagerly computed value.

### CODE REVIEW

**Comment by lemire** [comment]
Can you contribute a benchmark that would be representative of your workload?

From what I understand, you are spending a lot of time currently in this part of the code...

```java
  public boolean contains(RoaringBitmap subset) {
    if(subset.getCardinality() > getCardinality()) {
      return false;
    }
```

So it is the case that you are overwhelmingly checking if a small sets contains a large set (`small.contains(large)`). That's correct, right?


What kind of application logic leads you to such a kind of workload?

**Comment by lemire** [comment]
This being said, this part of our current code is probably suboptimal. It is probably not generally helpful. So we can improve this...

But the scenario where you are mostly just checking whether a small set contains a large set has me puzzled. It looks like you might be brute-forcing a problem of some kind.

**Comment by incaseoftrouble** [comment]
> Can you contribute a benchmark that would be representative of your workload?

Sure, I'll see if can extract something canonical. However, anything which doesn't compress too well should work (no compression -> cardinality is "linear" time -> `getCardinality` is slow).

So, for example, create a `large` bitset which has all the odd numbers 1 to 2n + 1 in it and a `small` one which only contains the number 2. Checking for cardinality in both `large.contains(small)` and `small.contains(large)` is much slower than directly checking for a "counterexample".

A different approach would be to have a dedicated `static boolean isLarger(Roarding a, Roaring b)` which traverses both a and b simultaneously until the end of one of the two is reached.

> `small.contains(large)`

Not necessarily, my workload is `large.contains(small)`. But contains has an early termination (find any element of `small` which is not in `large`) which apparently triggers quite often.

> What kind of application logic leads you to such a kind of workload?

Quite specific: I'm finding (maximal) end components on Markov decision processes.

Details, breaking it down to the Bitset level: I have system of (more or less) arbitrarily numbered states, each state has a list of sets of successors. For example `1 -> [{2, 3, 4}, {3, 4, 6}]` means that `1` can go to all of `2, 3, 4` or all of `3, 4, 6`. These successor sets are represented via bitsets. I know that this not ideal, since the data is somewhat random, however there indeed is some structure which makes roaring perform x3 better than using `(Sparse)BitSet` or even classical hash-based sets. Now I want to, essentially, find maximal sets of states which are closed under this successor relation, i.e. a set S such that for each state s in S there exists a successor set of s such that the successor set is a subset of S.

If I remember correctly, the classical algorithm for that is cubic in the number of states and you can get quadratic number of subset checks. In any case, its not unnatural to have a lot of subset checks in this particular instance.

I totally agree that this is quite specific, so I'd be fine with keeping this on a separate fork. However, I doubt that this has noticable performance impact in any case, and it allows for nice constant time short-cirtcuting on equals and contains.

**Comment by lemire** [comment]
@incaseoftrouble Can you have a look at a competing PR: 
https://github.com/RoaringBitmap/RoaringBitmap/pull/375

I did not understand the issue at first, but now I do, in part thanks to your great example. 

If both approaches fix your problem, then I think that the competing PR would be better since it removes code. Removing code is always better than adding it...

**Comment by incaseoftrouble** [comment]
> Removing code is always better than adding it...

True! #375 should also fix my problem. I guess caching the cardinality isn't too helpful since `cardinality()` probably is called rarely from the outside, anyway.

The optimization probably comes from "standard" sets, where `size()` usually is a constant time operation.

**Comment by lemire** [comment]
I will close your PR and merge the other one.

**Pull request closed without merging**
