### PR TITLE
Add test case to test unsignedIntersects() method

### PR DESCRIPTION
**Pull request by JunyuanZheng**
Hi, this is my first pull request, I will try to keep adding test cases to improve the coverage. If you have some suggestion please tell me.

Sincerely,

Junyuan Zheng

### CODE REVIEW

**Comment by lemire** [comment]
Excellent!

**Comment by lemire** [comment]
I'll merge this right away, as it can do no harm, but I would suggest you also cover BufferUtil/unsignedIntersects for symmetry.

**Comment by lemire** [comment]
Added your name to the list of contributors.

**Comment by JunyuanZheng** [comment]
Thanks! I will try to cover that!

**Pull request merged**
