### PR TITLE
Fix to avoid double copy in in-place array OR

### PR DESCRIPTION
**Pull request by amitdesai03**
**In case when we increased capacity, we used to follow below steps:**

1. increaseCapacity(Arrays.copyOf)   - Copy 1st time
2. System.arrayCopy to offset  - Copy 2nd time
3. Perform Union

**With changes, it saves 2 copies:**

1. - create new array. (No copy)
2. - Perform union with new array as destination

### CODE REVIEW

**Comment by lemire** [comment]
Looks good. Would you extend your work to the buffer class?

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java#L799-L802

It is mostly just copy-and-paste.

**Comment by lemire** [comment]
Reference: https://github.com/RoaringBitmap/RoaringBitmap/issues/225

**Comment by amitdesai03** [comment]
Sure, will do.

**Comment by lemire** [comment]
Please also add your name to 

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/AUTHORS

**Comment by lemire** [comment]
Or I can add your name later. But your name will need to be added.

**Comment by amitdesai03** [comment]
@lemire added changes, please check

**Comment by lemire** [comment]
Looks good. Will be part of the next release.

**Pull request merged**
