### PR TITLE
Replace emulated unsigned shorts with chars

### PR DESCRIPTION
**Pull request by richardstartin**
The main aim here is to make signedness bugs impossible, which are frequent in this library, by using Java's unsigned `char` type in place of `short`. This also leads to the elimination of methods `toIntUnsigned` and `compareUnsigned`, which will likely improve performance marginally. I will follow up with some rough benchmark numbers.

### CODE REVIEW

**Comment by lemire** [comment]
I love it. This is so incredibly clever.

@richardstartin Can you check the "2 for Useless comparison test" warnings that LGTM reported?

https://lgtm.com/projects/g/RoaringBitmap/RoaringBitmap/rev/pr-0eda70b1bd9843efdad8f13174a40fff20474957

**Comment by richardstartin** [comment]
The LGTM alerts are in existing code where the emulated unsigned types made the code too difficult to analyse. I'll remove these checks.

**Comment by lemire** [comment]
I see this. Neat.

**Comment by richardstartin** [comment]
There's still the 2 new useless checks to find - struggling with the LGTM interface because the offending classes are too large to render effectively, it seems.

**Comment by richardstartin** [comment]
LGTM is wrong about the introduced cases - I put a breakpoint in `RunContainer.smartAppendExclusive` and the final condition certainly is sometimes true (also obvious if you read the code below)

```java
  private void smartAppendExclusive(char start, char length) {
    int oldend;
    if ((nbrruns == 0)
        || ((start) > (oldend = (getValue(nbrruns - 1))
            + (getLength(nbrruns - 1)) + 1))) { // we add a new one
      valueslength[2 * nbrruns] = start;
      valueslength[2 * nbrruns + 1] = length;
      nbrruns++;
      return;
    }
    if (oldend == (start)) {
      // we merge
      valueslength[2 * (nbrruns - 1) + 1] += length + 1;
      return;
    }

    int newend = (start) + (length) + 1;

    if ((start) == (getValue(nbrruns - 1))) {
      // we wipe out previous
      if (newend < oldend) {
        setValue(nbrruns - 1, (char) newend);
        setLength(nbrruns - 1, (char) (oldend - newend - 1));
        return;
      } else if (newend > oldend) {
        setValue(nbrruns - 1, (char) oldend);
        setLength(nbrruns - 1, (char) (newend - oldend - 1));
        return;
      } else { // they cancel out
        nbrruns--;
        return;
      }
    }
    setLength(nbrruns - 1, (char) (start - (getValue(nbrruns - 1)) - 1));
    if (newend < oldend) {
      setValue(nbrruns, (char) newend);
      setLength(nbrruns, (char) (oldend - newend - 1));
      nbrruns++;
    } else if (newend > oldend) {
      setValue(nbrruns, (char) oldend);
      setLength(nbrruns, (char) (newend - oldend - 1));
      nbrruns++;
    }
  }
```

**Comment by lemire** [comment]
Ok. Then let us merge. 

I expect that we can’t go wrong (performance-wise).

**Comment by richardstartin** [comment]
Regarding performance, I ran some of the real data benchmarks (ForEach and Or) and found there were a few big improvements, but also some small regressions. I don't know why.

**Comment by lemire** [comment]
@richardstartin I take it that you recommend merging?

**Comment by richardstartin** [comment]
Yes I think so, we can revert if  performance regressions materialise.

**Comment by lemire** [comment]
Released.

**Pull request merged**
