### PR TITLE
Issue #498 - fix, when rank was called before adding first element, c…

### PR DESCRIPTION
**Pull request by novoj**
Proposed fix for https://github.com/RoaringBitmap/RoaringBitmap/issues/498.

### SUMMARY

All reasoning is discussed in referred issue.

### Automated Checks

- [ X] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [ X] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

### CODE REVIEW

**Comment by lemire** [comment]
It seems that we now have a glut of PRs.

@blacelle Can you check this new PR...

**Comment by blacelle** [comment]
This PR looks contained in https://github.com/RoaringBitmap/RoaringBitmap/pull/500. Plus, the style looks not OK (tab instead of 2-spaces). I feel this can be discarded. Thanks for your help @novoj.

**Comment by novoj** [comment]
Sorry for that - but we have different rules in my company. On my defense - I've run:

```
RoaringBitmap (master) $ ./gradlew checkstyleMain
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 7s
7 actionable tasks: 7 up-to-date
```

... and nothing has been reported. Thanks for fixing the problem.

**Comment by lemire** [comment]
@novoj Please keep the PRs coming. We appreciate your work.

**Pull request closed without merging**
