### PR TITLE
Remove dead code (#137)

### PR DESCRIPTION
**Pull request by arturowczarek**
* Checking buffer type after cloning MappeableBitmapContainer

### CODE REVIEW

**Comment by ppiotrow** [comment]
Looks good. I've tried and couldn't find any more lines matching this dead code pattern.

**Comment by lemire** [comment]
Good. Thanks @ppiotrow for the review.

**Comment by lemire** [comment]
@arturowczarek I'd like your confirmation that you want a merge of this PR now since you have been tweaking it a bit.

**Comment by arturowczarek** [comment]
@lemire You can merge

**Comment by lemire** [comment]
Merged.

**Pull request merged**
