### PR TITLE
fix: java.lang.ClassCastException

### PR DESCRIPTION
**Pull request by gpunti**
org.roaringbitmap.buffer.ImmutableRoaringBitmap cannot be cast to org.roaringbitmap.buffer.MutableRoaringBitmap

### CODE REVIEW

**Comment by lemire** [comment]
Thanks.

**Comment by lemire** [comment]
Fixed in release 0.5.20.

Thanks.

**Comment by lemire** [comment]
@gpunti 

Note that your membership to the RoaringBitmap organization is currently private: https://github.com/orgs/RoaringBitmap/people/gpunti

Given your valued contribution, you might want to make it public.

**Comment by gpunti** [comment]
Made public. I hadn't noticed it was private. Thanks.

**Pull request merged**
