### PR TITLE
bit slice index for java

### PR DESCRIPTION
**Pull request by Smallhi**

### CODE REVIEW

**Comment by richardstartin** [comment]
Is there any part of this implementation which needs to be in this library because it uses non-public APIs? I expect that most users won't use BSI indexes, and this will add more bloat to this library. Here's a jar size by version history:

| jar                                 | size  |
|--------------------------|------|
RoaringBitmap-0.1.0.jar | 80K 
RoaringBitmap-0.2.0.jar | 88K
RoaringBitmap-0.4.0.jar | 104K
RoaringBitmap-0.5.0.jar | 188K
RoaringBitmap-0.6.0.jar | 204K
RoaringBitmap-0.7.0.jar | 256K
RoaringBitmap-0.8.0.jar | 324K
RoaringBitmap-0.9.0.jar | 380K

Some of the bloat is caused by code duplication, but a lot of the time, the increases in size have been for features which only made sense to a subset of users (e.g. two incarnations of 64 bit support), and adding BSI functionality definitely falls in that category. If this is added, I think it should be in a separate sourceset with a `bsi` feature which users can opt in to if they want it.

**Comment by lemire** [comment]
> If this is added, I think it should be in a separate sourceset with a bsi feature which users can opt in to if they want it.

Surely, we can make `bsi` be a distinct artefact which depends on the main jar, right? That's how I would do it intuitively, and we already have two binary jars... adding a third one sounds quite ok. We could find a way, before the next release, to put bsi in its own artefact. I *think* that this means moving the bsi code into a distinct source directory.

cc @marshallpierce

**Comment by blacelle** [comment]
The code-bloat looks a relevant argument. I would not be keen forcing each such additional feature to be implement in their own repository. I feel comfortable with some sort of RoaringBitmap-extras jar.

**Comment by lemire** [comment]
@blacelle That's easily resolved. I will merge to a distinct branch and see what can be done.

**Comment by lemire** [comment]
Merging to a temporary branch.

**Comment by lemire** [comment]
See https://github.com/RoaringBitmap/RoaringBitmap/pull/496

**Pull request merged**
