### PR TITLE
make it possible to disable on the fly run compression

### PR DESCRIPTION
**Pull request by richardstartin**
Adds a flag to prevent container appenders from run length encoding the appended container.

### CODE REVIEW

**Comment by richardstartin** [comment]
clearly need to cover the new branch in a few places

**Comment by richardstartin** [comment]
@lemire the background here is that when using the bitmap writer to streamline sequential construction of bitmaps the API user no longer gets a choice about run compression, it just happens anyway, which has space/time tradeoffs in some cases.

**Comment by lemire** [comment]
This looks good to me.

**Comment by richardstartin** [comment]
Thanks @lemire could you do a release with these changes when it's convenient for you?

**Comment by lemire** [comment]
@richardstartin Done.

**Pull request merged**
