### PR TITLE
implement intersects with range

### PR DESCRIPTION
**Pull request by richardstartin**
Just knocked this up quickly. Let me know if there are obvious algorithmic improvements.

### CODE REVIEW

**Comment by lemire** [comment]
Presumably, your code checks for intersections with the interval [min,max). Right? It is not clearly specified. But if so, then you have the problem that 1<<32 cannot be expressed. That's why we use longs elsewhere in the API.

(Recall that we interpret Java's ints as unsigned integers.)

**Comment by lemire** [comment]
(Other than that, the code is superb.)

**Comment by lemire** [comment]
You are correct and I was wrong, the specification is there... note however the typo:

>   param supremum the exlusive unsigned upper bound of the range

But my objection still stand since you can't capture the whole range [0,1<<32).

**Comment by richardstartin** [comment]
I agree with you. I've just made those changes.

**Comment by lemire** [comment]
In the past, people have felt strongly that the ranges should be checked. So we have a function called ``rangeSanityCheck``. Do you want to have a look?

**Comment by lemire** [comment]
(I can merge and add the check later if you'd prefer. But I suspect that some people really want the check.)

**Comment by richardstartin** [comment]
I'm not sure there's much left to do on this, I'm happy for it to be merged.

**Comment by lemire** [comment]
I agree. This looks (very) excellent to me.

**Pull request merged**
