### PR TITLE
remove indirection between logic and data in RoaringBitmap

### PR DESCRIPTION
**Pull request by richardstartin**
This replaces composition of `RoaringArray` with inheritance. This is usually a bad idea, but it should lead to performance improvements. There are some software engineering aspects to look out for, such as being sure the public interface is not extended.

### CODE REVIEW

**Comment by richardstartin** [comment]
@lemire I need to clean the commits up because I clobbered your latest change in the merge.

**Comment by richardstartin** [comment]
I can't see any evidence that this actually improves performance. It probably requires more careful benchmarking. I will leave the branch here in case anyone else is tempted to try the same thing in the future.

**Comment by lemire** [comment]
Can't this be justified on the basis of software engineering (code maintenance, and so forth)?

**Comment by richardstartin** [comment]
Some might say code reuse through inheritance is bad. I only took it this far to see if there was a performance boost, couldn’t find one in micro benchmarks, but would be interested in how it affects a production application. I can clean it up a bit if there are no objections to the approach. It makes space for a cached cardinality instead of the reference too.

**Pull request closed without merging**
