### PR TITLE
Proposed fix - Avoid double copy in in-place array add

### PR DESCRIPTION
**Pull request by amitdesai03**

### CODE REVIEW

**Comment by amitdesai03** [comment]
Reference: https://github.com/RoaringBitmap/RoaringBitmap/issues/231

**Comment by amitdesai03** [comment]
Ran iadd benchmarks against huge list of ranges:

**Before**

Benchmark         Mode  Cnt      Score      Error  Units
AddBenchmark.add  avgt    5  57538.034 ± 2756.394  us/op

**After**:

Benchmark         Mode  Cnt      Score      Error  Units
AddBenchmark.add  avgt    5  55455.495 ± 2795.335  us/op

**Comment by lemire** [comment]
@amitdesai03 Please run ``mvn checkstyle:check`` on your code. It appears that you have style violation. We enforce a strict style. (It avoids having to deal with folks reformatting the code according to their favourite style.)

**Comment by amitdesai03** [comment]
@lemire yes I understand, I actually checked in with lot of comments so as you can review. 
If i format it, it just makes comments reading harder. I was thinking that after your review, i will checkin with checkstyle complaint version. But if you want, i can checkin right away?

**Here is more accurate benchmark, which shows definite improvement by :**

Benchmark                  Mode  Cnt     Score     Error  Units
AddBenchmark.add           avgt   20  5712.009 ± 104.209  us/op
AddBenchmark.addOptimized  avgt   20  5684.183 ±  49.245  us/op

I am not sure if I should checkin benchmarking code, as it introduces new random range set to real data set directory?

**Comment by lemire** [comment]
> I am not sure if I should checkin benchmarking code, as it introduces new random range set to real data set directory?

Can you elaborate? I am not sure I understand why you are hesitating to include your benchmarking code?

**Comment by amitdesai03** [comment]
Since name represented real data set, what i have is generated data set based on randomization. Also have custom zip reader for ranges in contrast to what exists already.

I will check in all, you be the judge :), lemme know if needs some modification

**Comment by lemire** [comment]
Good.

**Comment by amitdesai03** [comment]
done, pls verify

**Comment by lemire** [comment]
I think this solves it. Great work.

**Comment by amitdesai03** [comment]
tx, learned quite few things like jmh and shortbuffer

**Pull request merged**
