### PR TITLE
make getLength and getValue public

### PR DESCRIPTION
**Pull request by richardstartin**
I have found that if calling code "knows" about runs, it's much easier to make the code as fast as possible. I imagine there will be some pushback on this. This is a small, low risk change, but might evoke strong feelings from a software engineering point of view.

### CODE REVIEW

**Comment by lemire** [comment]
Thanks!

**Comment by richardstartin** [comment]
Thoughts?

**Comment by lemire** [comment]
I have no problem with this code, but would you be so kind as to add documentation to these methods. Because these functions become public, it should be expected that users can find documentation.

If you can't, somehow, document them from your end, I'll merge and document.

**Comment by richardstartin** [comment]
I will add some JavaDoc this weekend

**Comment by richardstartin** [comment]
Done (fixed up onto the original commit).

**Comment by ppiotrow** [comment]
For consistency please add public to `MappeableRunContainer.java`.

**Comment by richardstartin** [comment]
To be honest I'm only changing this in `RunContainer` because I actually use the class.

**Comment by lemire** [comment]
I think it is now a no-brainer.

**Comment by richardstartin** [comment]
Thanks for keeping me honest with the thorough review.

**Pull request merged**
